services:
  db:
    ports:
    - '3306:3306'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
  server:
    depends_on:
      - db
    ports:
      - '8080:8080'
    build:
      context: .
      args:
        USER: 'admin'
        PASS: 'password'
        HOST: 'db'
        PORT: '3306'
        DB: 'db'
        TIMEOUT: '20'
