#Simple and easy local testing of code without worrying about cloud deployment
#Code should be modular enough to work irrigardless of cloud deployment and vice-versa
version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
  server:
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: server_Dockerfile
      args:
        USER: 'admin'
        PASS: 'password'
        HOST: 'db'
        PORT: '3306'
        DB: 'db'
        TIMEOUT: '20'
